#include <math.h>

enum {
    FP_NAN = FP_NAN,
    FP_INFINITE = FP_INFINITE,
    FP_ZERO = FP_ZERO,
    FP_SUBNORMAL = FP_SUBNORMAL,
    FP_NORMAL = FP_NORMAL
};

/* the following functions are defined via macros, so explicit definitions are used */
extern double      acos(double);
extern float       acosf(float);
extern double      acosh(double);
extern float       acoshf(float);
extern long double acoshl(long double);
extern long double acosl(long double);
extern double      asin(double);
extern float       asinf(float);
extern double      asinh(double);
extern float       asinhf(float);
extern long double asinhl(long double);
extern long double asinl(long double);
extern double      atan(double);
extern double      atan2(double, double);
extern float       atan2f(float, float);
extern long double atan2l(long double, long double);
extern float       atanf(float);
extern double      atanh(double);
extern float       atanhf(float);
extern long double atanhl(long double);
extern long double atanl(long double);
extern double      cbrt(double);
extern float       cbrtf(float);
extern long double cbrtl(long double);
extern double      ceil(double);
extern float       ceilf(float);
extern long double ceill(long double);
extern double      copysign(double, double);
extern float       copysignf(float, float);
extern long double copysignl(long double, long double);
extern double      cos(double);
extern float       cosf(float);
extern double      cosh(double);
extern float       coshf(float);
extern long double coshl(long double);
extern long double cosl(long double);
extern double      erf(double);
extern double      erfc(double);
extern float       erfcf(float);
extern long double erfcl(long double);
extern float       erff(float);
extern long double erfl(long double);
extern double      exp(double);
extern double      exp2(double);
extern float       exp2f(float);
extern long double exp2l(long double);
extern float       expf(float);
extern long double expl(long double);
extern double      expm1(double);
extern float       expm1f(float);
extern long double expm1l(long double);
extern double      fabs(double);
extern float       fabsf(float);
extern long double fabsl(long double);
extern double      fdim(double, double);
extern float       fdimf(float, float);
extern long double fdiml(long double, long double);
extern double      floor(double);
extern float       floorf(float);
extern long double floorl(long double);
extern double      fma(double, double, double);
extern float       fmaf(float, float, float);
extern long double fmal(long double, long double, long double);
extern double      fmax(double, double);
extern float       fmaxf(float, float);
extern long double fmaxl(long double, long double);
extern double      fmin(double, double);
extern float       fminf(float, float);
extern long double fminl(long double, long double);
extern double      fmod(double, double);
extern float       fmodf(float, float);
extern long double fmodl(long double, long double);
extern double      frexp(double, int *);
extern float       frexpf(float, int *);
extern long double frexpl(long double, int *);
extern double      hypot(double, double);
extern float       hypotf(float, float);
extern long double hypotl(long double, long double);
extern int         ilogb(double);
extern int         ilogbf(float);
extern int         ilogbl(long double);
extern double      j0(double);
extern double      j1(double);
extern double      jn(int, double);
extern double      ldexp(double, int);
extern float       ldexpf(float, int);
extern long double ldexpl(long double, int);
extern double      lgamma(double);
extern float       lgammaf(float);
extern long double lgammal(long double);
extern long long   llrint(double);
extern long long   llrintf(float);
extern long long   llrintl(long double);
extern long long   llround(double);
extern long long   llroundf(float);
extern long long   llroundl(long double);
extern double      log(double);
extern double      log10(double);
extern float       log10f(float);
extern long double log10l(long double);
extern double      log1p(double);
extern float       log1pf(float);
extern long double log1pl(long double);
extern double      log2(double);
extern float       log2f(float);
extern long double log2l(long double);
extern double      logb(double);
extern float       logbf(float);
extern long double logbl(long double);
extern float       logf(float);
extern long double logl(long double);
extern long        lrint(double);
extern long        lrintf(float);
extern long        lrintl(long double);
extern long        lround(double);
extern long        lroundf(float);
extern long        lroundl(long double);
extern double      modf(double, double *);
extern float       modff(float, float *);
extern long double modfl(long double, long double *);
extern double      nan(const char *);
extern float       nanf(const char *);
extern long double nanl(const char *);
extern double      nearbyint(double);
extern float       nearbyintf(float);
extern long double nearbyintl(long double);
extern double      nextafter(double, double);
extern float       nextafterf(float, float);
extern long double nextafterl(long double, long double);
extern double      nexttoward(double, long double);
extern float       nexttowardf(float, long double);
extern long double nexttowardl(long double, long double);
extern double      pow(double, double);
extern float       powf(float, float);
extern long double powl(long double, long double);
extern double      remainder(double, double);
extern float       remainderf(float, float);
extern long double remainderl(long double, long double);
extern double      remquo(double, double, int *);
extern float       remquof(float, float, int *);
extern long double remquol(long double, long double, int *);
extern double      rint(double);
extern float       rintf(float);
extern long double rintl(long double);
extern double      round(double);
extern float       roundf(float);
extern long double roundl(long double);
extern double      scalbln(double, long);
extern float       scalblnf(float, long);
extern long double scalblnl(long double, long);
extern double      scalbn(double, int);
extern float       scalbnf(float, int);
extern long double scalbnl(long double, int);
extern double      sin(double);
extern float       sinf(float);
extern double      sinh(double);
extern float       sinhf(float);
extern long double sinhl(long double);
extern long double sinl(long double);
extern double      sqrt(double);
extern float       sqrtf(float);
extern long double sqrtl(long double);
extern double      tan(double);
extern float       tanf(float);
extern double      tanh(double);
extern float       tanhf(float);
extern long double tanhl(long double);
extern long double tanl(long double);
extern double      tgamma(double);
extern float       tgammaf(float);
extern long double tgammal(long double);
extern double      trunc(double);
extern float       truncf(float);
extern long double truncl(long double);
extern double      y0(double);
extern double      y1(double);
extern double      yn(int, double);
